openapi: 3.0.0
info:
  title: Inventory Management API
  description: API for managing inventory objects, including create, update, and delete operations.
  version: 1.0.0
servers:
  - url: 'http://localhost:3015/api'
paths:
  /inventory-objects/{id}:
    delete:
      summary: Delete an inventory object by id.
      parameters:
        - name: id
          in: path
          description: ID of the inventory object to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Inventory object deleted successfully
        '404':
          description: Inventory object not found
        '500':
          description: Server error
