openapi: 3.0.0
info:
  title: Inventory Management API
  description: API to manage inventory objects.
  version: 1.0.0
servers:
  - url: 'http://localhost:3016/api'
paths:
  /inventory-objects:
    get:
      summary: Get all inventory objects
      responses:
        '200':
          description: A list of inventory objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    objectType:
                      type: string
                    quantity:
                      type: integer
                    status:
                      type: string
        '404':
          description: No inventory objects found
        '500':
          description: Server error.
