name: CI Pipeline Inventory Objects Delete

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker Image
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/inventoryobjectsdelete:dev ./inventoryObjectsDelete
          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/inventoryobjectsdelete:prod ./inventoryObjectsDelete
          elif [[ "${{ github.event.pull_request.base.ref }}" == "QA" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/inventoryobjectsdelete:qa ./inventoryObjectsDelete
          else
            echo "Invalid branch for building Docker image."
            exit 1

      - name: Push to DockerHub
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/inventoryobjectsdelete:dev
          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/inventoryobjectsdelete:prod
          elif [[ "${{ github.event.pull_request.base.ref }}" == "QA" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/inventoryobjectsdelete:qa
          fi
