name: CI Pipeline Inventory Objects Create

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
          
    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      
    - name: Build the Docker image
      run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:dev .
          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:prod .
          elif [[ "${{ github.event.pull_request.base.ref }}" == "QA" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:qa .
          else
            echo "Invalid branch for building Docker image."
            exit 1
          fi
          
    - name: Push to DockerHub
      run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:dev
          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:prod
          elif [[ "${{ github.event.pull_request.base.ref }}" == "QA" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:qa
          fi
