name: CI Pipeline Inventory Objects Create

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
          
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Exclude docs and swagger.yaml for main
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        run: |
          # Exclude docs/ and swagger.yaml when in `main` or when doing pull request to main
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            rm -rf ./inventoryObjectsCreate/src/docs
          fi
          
          # If it is a pull request to main from dev or QA, also exclude the files
          if [[ "${{ github.event_name }}" == "pull_request" && ( "${{ github.event.pull_request.base.ref }}" == "main" ) ]]; then
            rm -rf ./inventoryObjectsCreate/src/docs
          fi

      - name: Build the Docker image
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:dev ./inventoryObjectsCreate
          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:prod ./inventoryObjectsCreate
          elif [[ "${{ github.event.pull_request.base.ref }}" == "QA" ]]; then
            docker build -t ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:qa ./inventoryObjectsCreate
          else
            echo "Invalid branch for building Docker image."
            exit 1
          fi
          
      - name: Push to DockerHub
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:dev
          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:prod
          elif [[ "${{ github.event.pull_request.base.ref }}" == "QA" ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/inventoryobjectscreate:qa
          fi
